class Constants(object):
    # Const
    EXIT_SUCCESS = 0
    EXIT_ERR_BAD_OPTION = 1
    EXIT_ERR_LOAD_CONFIG = 2
    EXIT_ERR_VCENTER_CONNECT_TIMEOUT_FAIL = 3
    EXIT_ERR_VCENTER_CONNECT_HOSTNAMRE_RESOLVE_FAIL = 4
    EXIT_ERR_VCENTER_CONNECT_LOGIN_FAIL = 5
    EXIT_ERR_VCENTER_CONNECT_REFUSED_FAIL = 6
    EXIT_ERR_VCENTER_CONNECT_UNKNOWN_FAIL = 9
    EXIT_ERR_INVALID_DATE_FORMAT = 10
    EXIT_ERR_UNKNOWN = 99
